apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: astra-frontend
  name: astra-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: astra-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: astra-frontend
    spec:
      containers:
        - image: astra-frontend
          name: astra-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
