name: "project-astra"
services: 
  llm-server:
    platform: linux/amd64
    build: ./llm-server/
    env_file: ./llm-server/.env
    ports:
      - 8080:8080
  
  react-flow-app: 
    platform: linux/amd64
    build: ./react-flow-app/
    ports: 
      - 4173:4174
  
  streamlit-app: 
    platform: linux/amd64
    build: ./streamlit-app 
    env_file: ./streamlit-app/.env
    ports: 
      - 8051:8051

  astra-frontend: 
    platform: linux/amd64 
    build: ./astra-frontend
    env_file: ./astra-frontend/.env
    ports: 
      - 3000:3000 
    
