apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: llm-server
  name: llm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llm-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: llm-server
    spec:
      containers:
        - env:
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: BUCKET_NAME
                  name: llm-server-env
            - name: FILE_ID
              valueFrom:
                configMapKeyRef:
                  key: FILE_ID
                  name: llm-server-env
            - name: FIREBASE_CLIENT
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_CLIENT
                  name: llm-server-env
            - name: FIREBASE_SERVER
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_SERVER
                  name: llm-server-env
            - name: GEMINI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: GEMINI_API_KEY
                  name: llm-server-env
            - name: GROQ_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: GROQ_API_KEY
                  name: llm-server-env
            - name: HF_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: HF_TOKEN
                  name: llm-server-env
            - name: LLM_API_URL
              valueFrom:
                configMapKeyRef:
                  key: LLM_API_URL
                  name: llm-server-env
            - name: MY_GEMINI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MY_GEMINI_API_KEY
                  name: llm-server-env
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: llm-server-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: llm-server-env
            - name: REACT_FLOW_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_FLOW_APP_URL
                  name: llm-server-env
            - name: STREAMLIT_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: STREAMLIT_APP_URL
                  name: llm-server-env
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: URL
                  name: llm-server-env
          image: llm-server
          name: llm-server
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
