apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: streamlit-app
  name: streamlit-app
spec:
  ports:
    - name: "8051"
      port: 8051
      targetPort: 8051
  selector:
    io.kompose.service: streamlit-app
