apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: streamlit-app
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: streamlit-app
    spec:
      containers:
        - env:
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: BUCKET_NAME
                  name: streamlit-app-env
            - name: FILE_ID
              valueFrom:
                configMapKeyRef:
                  key: FILE_ID
                  name: streamlit-app-env
            - name: FIREBASE_CLIENT
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_CLIENT
                  name: streamlit-app-env
            - name: FIREBASE_SERVER
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_SERVER
                  name: streamlit-app-env
            - name: GEMINI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: GEMINI_API_KEY
                  name: streamlit-app-env
            - name: GROQ_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: GROQ_API_KEY
                  name: streamlit-app-env
            - name: HF_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: HF_TOKEN
                  name: streamlit-app-env
            - name: LLM_API_URL
              valueFrom:
                configMapKeyRef:
                  key: LLM_API_URL
                  name: streamlit-app-env
            - name: MY_GEMINI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MY_GEMINI_API_KEY
                  name: streamlit-app-env
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: streamlit-app-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: streamlit-app-env
            - name: REACT_FLOW_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_FLOW_APP_URL
                  name: streamlit-app-env
            - name: STREAMLIT_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: STREAMLIT_APP_URL
                  name: streamlit-app-env
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: URL
                  name: streamlit-app-env
          image: streamlit-app
          name: streamlit-app
          ports:
            - containerPort: 8051
              protocol: TCP
      restartPolicy: Always
