name: Deploying Astra-Frontend to Artifact Registry

on: 
  push: 
    branches: 
      - main 
  
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v2 
      
      - name: Installing the gcloud cli 
        uses: google-github-actions/setup-gcloud@v0
        with: 
          project_id: ${{ secrets.GCP_PROJECT_ID }}  
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Pushing to docker using the CLI 
        env: 
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} 
          REGION: ${{ secrets.REGION }} 
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker-pkg.dev
          docker build -t ${{ env.REGION }}-docker-pkg.dev/${{ env.PROJECT_ID }}/astra-frontend/node:latest ./astra-frontend
          docker push ${{ env.REGION }}-docker-pkg.dev/${{ env.PROJECT_ID }}/astra-frontend/node:latest  

