name: Deploying Astra-Frontend to Artifact Registry

on: 
  push: 
    branches: 
      - main 
  
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v2 
      
      - name: Installing the gcloud cli 
        uses: google-github-actions/setup-gcloud@v2
        with: 
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}  
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      
      - name: Pushing to docker using the CLI 
        env: 
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} 
        run: |
          gcloud auth configure-docker us-central1-docker-pkg.dev
          docker build -t us-central1-docker-pkg.dev/${{ env.PROJECT_ID }}/astra-frontend/node-frontend ./astra-frontend
          docker push us-central1-docker-pkg.dev/${{ env.PROJECT_ID }}/astra-frontend/node-frontend  

