# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FastAPI endpoint  
on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install primary dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint 
        sudo apt install poppler-utils 

    - name: Setting up the dependencies for llm-server application 
      run: |  
        pip install -r ./llm-server/requirements.txt
        mkdir -p ./llm-server/.secrets
        echo ${{ secrets.GCP_BUCKET }} > ./llm-server/gcp_bucket.json
    
    - name: Setting up the streamlit application 
      run: |
        pip install -r ./streamlit-app/requirements.txt
        mkdir -p ./streamlit-app/.secrets
        echo ${{ secrets.GCP_BUCKET }} > ./streamlit-app/gcp_bucket.json
        echo ${{ secrets.FIREBASE_CLIENT }} > ./streamlit-app/firebase_cleint.json
