# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FastAPI endpoint  
on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint 
        sudo apt install poppler-utils 
        make install 
    - name: Lint with Pylint
      run: |
        pylint --disable=R,C *.py || true 
    - name: Intialize the Server 
      run: |
        fastapi run main.py & sleep 5
    - name: Checking the status of the output
      run: |
        python test.py 

    - name: Test with pytest
      run: |
        pytest test.py 
